name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of n8n-nodes-ewelink-v2 are you using?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: n8n-version
    attributes:
      label: n8n Version
      description: Which version of n8n are you using?
      placeholder: e.g., 1.0.0

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
